# Generated by Django 5.2.8 on 2025-12-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique de la catégorie', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='planned', max_length=20),
        ),
    ]
