# Generated by Django 5.2.8 on 2026-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_postal_code_supplier_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_credit_payment',
            field=models.BooleanField(default=False, verbose_name='Credit payé'),
        ),
        migrations.DeleteModel(
            name='CreditPayment',
        ),
    ]
