# Generated by Django 5.2.8 on 2026-01-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_payment_is_credit_payment_delete_creditpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
    ]
