# Generated by Django 5.2.8 on 2025-12-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sales_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Vente associée (automatique pour les sorties de vente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.sale'),
        ),
    ]
