# Generated by Django 5.2.8 on 2026-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_creditsale_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('stock_warning', 'Avertissement stock'), ('low_stock', 'Stock bas'), ('out_of_stock', 'Rupture de stock'), ('overstock', 'Surstock'), ('high_value_low_stock', 'Produit de valeur en stock faible'), ('no_movement', 'Aucun mouvement'), ('expiring_soon', 'Expiration proche')], max_length=20),
        ),
    ]
