# Generated by Django 5.2.8 on 2025-12-27 20:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_sale_to_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro de suivi'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Transporteur'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de transport'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_included',
            field=models.BooleanField(default=False, verbose_name='Frais de transport inclus dans le prix des produits'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('', 'Non spécifié'), ('routier', 'Routier'), ('maritime', 'Maritime'), ('aerien', 'Aérien'), ('ferroviaire', 'Ferroviaire'), ('retrait', 'Retrait sur place')], default='', max_length=50, verbose_name='Mode de transport'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes transport'),
        ),
    ]
