# Generated by Django 5.2.8 on 2025-12-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_transport_fields_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Commande associée (automatique pour les entrées de réception)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.order'),
        ),
    ]
