# Generated by Django 5.2.8 on 2025-11-27 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique de la permission (ex: hr.view_employee)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nom lisible de la permission', max_length=200)),
                ('category', models.CharField(help_text='Catégorie de la permission (ex: Employés, Départements)', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'hr_permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions personnalisées supplémentaires pour cet employé', related_name='employees_with_permission', to='hr.permission'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique du rôle (ex: super_admin, hr_manager)', max_length=100)),
                ('name', models.CharField(help_text='Nom du rôle', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='Rôle système prédéfini (non modifiable)')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organisation (null pour les rôles système)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions associées à ce rôle', related_name='roles', to='hr.permission')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'hr_roles',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Rôle attribué à cet employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.role'),
        ),
    ]
