# Generated by Django 4.2.11 on 2026-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladvance',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('deducted', 'Déduite')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
