# Generated by Django 4.2.11 on 2026-01-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_make_payment_date_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-created_at', 'employee__last_name'], 'verbose_name': 'Fiche de paie', 'verbose_name_plural': 'Fiches de paie'},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payslip',
            name='description',
            field=models.CharField(blank=True, help_text="Description ou titre de la fiche de paie (ex: 'Paie Janvier 2026', 'Prime exceptionnelle')", max_length=255),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollperiod'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['created_at'], name='payslips_created_9d7f00_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll_period__isnull', False)), fields=('employee', 'payroll_period'), name='unique_employee_period'),
        ),
    ]
