# Generated by Django 5.2.8 on 2025-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_permission_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'CDI - Contrat à Durée Indéterminée'), ('temporary', 'CDD - Contrat à Durée Déterminée'), ('contract', 'Contractuel'), ('internship', 'Stage'), ('freelance', 'Freelance/Consultant')], max_length=20),
        ),
    ]
