# Generated by Django 5.2.8 on 2025-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_address_employee_city_employee_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict, help_text="Contact d'urgence (name, phone, relationship)", null=True),
        ),
    ]
