# Generated by Django 5.2.8 on 2026-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_add_parent_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
