# Generated by Django 5.2.8 on 2025-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
