# Generated by Django 5.2.8 on 2026-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_contract_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='title',
            field=models.CharField(blank=True, help_text='Titre descriptif de la demande', max_length=200),
        ),
    ]
