# Generated by Django 5.2.8 on 2025-11-30 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0005_alter_employee_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approver',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvers', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
