# Generated by Django 5.2.8 on 2025-12-04 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_leaverequest_approver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(help_text='Date du pointage')),
                ('check_in', models.DateTimeField(blank=True, help_text="Heure d'arrivée", null=True)),
                ('check_in_location', models.CharField(blank=True, help_text="Localisation du pointage d'arrivée", max_length=255)),
                ('check_in_notes', models.TextField(blank=True, help_text="Notes lors du pointage d'arrivée")),
                ('check_out', models.DateTimeField(blank=True, help_text='Heure de départ', null=True)),
                ('check_out_location', models.CharField(blank=True, help_text='Localisation du pointage de départ', max_length=255)),
                ('check_out_notes', models.TextField(blank=True, help_text='Notes lors du pointage de départ')),
                ('break_start', models.DateTimeField(blank=True, help_text='Début de pause', null=True)),
                ('break_end', models.DateTimeField(blank=True, help_text='Fin de pause', null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Heures totales travaillées', max_digits=5, null=True)),
                ('break_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Durée de pause en heures', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('half_day', 'Demi-journée'), ('on_leave', 'En congé')], default='present', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Pointage approuvé par le manager')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Heures supplémentaires', max_digits=5)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'attendances',
                'ordering': ['-date', '-check_in'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendances_employe_993bac_idx'), models.Index(fields=['date', 'status'], name='attendances_date_684e3c_idx'), models.Index(fields=['employee', 'status'], name='attendances_employe_778425_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
