# Generated by Django 5.2.8 on 2026-02-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_make_leaverequest_leavetype_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
