# Generated by Django 5.2.8 on 2025-12-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('hr', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendances_employe_778425_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text="Type d'utilisateur (Employee ou AdminUser)", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='object_id',
            field=models.UUIDField(blank=True, help_text="ID de l'utilisateur", null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organisation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.organization'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_email',
            field=models.EmailField(blank=True, default='', help_text="Email de l'utilisateur (cached)", max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_full_name',
            field=models.CharField(blank=True, default='', help_text="Nom complet de l'utilisateur (cached)", max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employé (pour les comptes Employee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['organization', 'date'], name='attendances_organiz_2acbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user_email', 'date'], name='attendances_user_em_22cb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['content_type', 'object_id', 'date'], name='attendances_content_d9de9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('organization', 'user_email', 'date'), name='unique_user_date_attendance'),
        ),
    ]
