# Generated by Django 5.2.8 on 2025-12-04 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_attendance_attendances_employe_778425_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', help_text="Statut d'approbation du pointage", max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin qui a approuvé/rejeté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Raison du rejet (optionnel)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Employé qui a approuvé/rejeté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to='hr.employee'),
        ),
    ]
