# Generated by Django 5.2.8 on 2025-12-05 16:59

from django.db import migrations, models
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_attendance_approval_status_and_more'),
    ]

    operations = [
        # 1. Supprimer les anciens champs de Payslip
        migrations.RemoveField(
            model_name='payslip',
            name='overtime_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='social_security',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_deductions',
        ),

        # 2. Modifier les champs calculés de Payslip pour avoir des valeurs par défaut
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire brut = base + primes', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total des déductions', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire net = brut - déductions', max_digits=12),
        ),

        # 3. Supprimer les anciens champs de PayslipItem
        migrations.RemoveField(
            model_name='payslipitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='payslipitem',
            name='total',
        ),

        # 4. Ajouter les nouveaux champs à PayslipItem
        migrations.AddField(
            model_name='payslipitem',
            name='name',
            field=models.CharField(default='', help_text="Nom de l'élément (ex: Prime de transport)", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='is_deduction',
            field=models.BooleanField(default=False, help_text="True si c'est une déduction, False si c'est une prime"),
        ),

        # 5. Modifier le champ amount (garde la même structure mais on le redéfinit pour être sûr)
        migrations.AlterField(
            model_name='payslipitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Montant de l'élément", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
