# Generated by Django 5.2.8 on 2026-03-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_add_leave_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(blank=True, help_text='Null = solde global, renseigné = solde par type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('leave_type__isnull', False)), fields=('employee', 'leave_type', 'year'), name='unique_balance_per_type'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('leave_type__isnull', True)), fields=('employee', 'year'), name='unique_global_balance'),
        ),
    ]
