# Generated by Django 5.2.8 on 2025-12-07 00:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0010_refactor_payslip_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslipitem',
            options={'ordering': ['is_deduction', 'name'], 'verbose_name': 'Ligne de fiche de paie', 'verbose_name_plural': 'Lignes de fiches de paie'},
        ),
        migrations.AlterField(
            model_name='payslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Salaire de base mensuel', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='leave_days_taken',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jours de congé pris pendant la période', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures supplémentaires', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Heures travaillées dans la période', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='QRCodeSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, help_text='Token unique pour cette session', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text="Date et heure d'expiration de la session")),
                ('is_active', models.BooleanField(default=True, help_text='Si False, la session ne peut plus être utilisée')),
                ('created_by', models.ForeignKey(help_text='Administrateur qui a créé cette session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_sessions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employé pour qui ce QR est généré', on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='hr.employee')),
                ('organization', models.ForeignKey(help_text='Organisation de la session', on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='core.organization')),
            ],
            options={
                'verbose_name': 'Session QR Code',
                'verbose_name_plural': 'Sessions QR Code',
                'db_table': 'hr_qr_code_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token'], name='hr_qr_code__session_109afe_idx'), models.Index(fields=['expires_at'], name='hr_qr_code__expires_9d7ec9_idx'), models.Index(fields=['is_active'], name='hr_qr_code__is_acti_671533_idx')],
            },
        ),
    ]
