# Generated by Django 5.2.8 on 2025-12-16 22:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_payslipitem_options_alter_payslip_base_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Montant de l'avance demandée", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(help_text="Raison de la demande d'avance")),
                ('request_date', models.DateField(auto_now_add=True, help_text='Date de la demande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', help_text='Statut de la demande', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, help_text="Date d'approbation/rejet", null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet (si applicable)')),
                ('payment_date', models.DateField(blank=True, help_text='Date du paiement effectif', null=True)),
                ('deduction_month', models.DateField(blank=True, help_text='Mois prévu pour la déduction', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Employé ayant approuvé la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to='hr.employee')),
                ('employee', models.ForeignKey(help_text="Employé demandant l'avance", on_delete=django.db.models.deletion.CASCADE, related_name='payroll_advances', to='hr.employee')),
                ('payslip', models.ForeignKey(blank=True, help_text="Fiche de paie où l'avance a été déduite", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_deducted', to='hr.payslip')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_payrolla_employe_80bb40_idx'), models.Index(fields=['request_date'], name='hr_payrolla_request_7e9276_idx'), models.Index(fields=['status'], name='hr_payrolla_status_07fad6_idx')],
            },
        ),
    ]
