# Generated by Django 5.2.8 on 2026-03-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_add_break_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact',
        ),
    ]
