# Generated by Django 5.2.8 on 2025-12-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_payrolladvance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladvance',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée'), ('deducted', 'Déduite (Close)')], default='pending', help_text='Statut de la demande', max_length=20),
        ),
    ]
