# Generated by Django 5.2.8 on 2025-12-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_update_payroll_advance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesession',
            name='allowed_employees',
            field=models.ManyToManyField(blank=True, help_text='Employés autorisés à utiliser ce QR code', related_name='allowed_qr_sessions', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='qrcodesession',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employé principal (backward compat)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='hr.employee'),
        ),
    ]
