# Generated by Django 5.2.8 on 2026-04-13 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_employee_invitation'),
        ('hr', '0013_remove_duplicate_personal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(help_text="Email de l'employee invité", max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(editable=False, help_text="Token sécurisé pour l'activation", max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration de l'invitation")),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_message', models.TextField(blank=True, help_text="Message personnalisé de l'administrateur")),
                ('resent_count', models.IntegerField(default=0, help_text="Nombre de fois que l'invitation a été renvoyée")),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_role', models.ForeignKey(blank=True, help_text="Rôle qui sera attribué à l'employee", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('employee', models.ForeignKey(blank=True, help_text="Employee créé suite à l'acceptation (null si pas encore acceptée)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='hr.employee')),
                ('invited_by', models.ForeignKey(help_text="Administrateur qui a envoyé l'invitation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='core.baseuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_invitations', to='core.organization')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.position')),
            ],
            options={
                'verbose_name': 'Invitation Employee',
                'verbose_name_plural': 'Invitations Employee',
                'db_table': 'employee_invitations',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='employee_in_organiz_4f7e3c_idx'), models.Index(fields=['email'], name='employee_in_email_7ee146_idx'), models.Index(fields=['token'], name='employee_in_token_d9cfd5_idx'), models.Index(fields=['expires_at'], name='employee_in_expires_63a438_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invitation_per_email')],
            },
        ),
    ]
