# Generated by Django 5.2.8 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_qrcodesession_allowed_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesession',
            name='mode',
            field=models.CharField(
                choices=[
                    ('auto', 'Auto (détection automatique)'),
                    ('check_in', 'Arrivée uniquement'),
                    ('check_out', 'Départ uniquement'),
                ],
                default='auto',
                help_text='Mode de pointage: auto, check_in, ou check_out',
                max_length=20,
            ),
        ),
    ]
