# Generated by Django 5.2.8 on 2026-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_employee_invitation'),
        ('hr', '0014_add_employee_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvitation',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions personnalisées supplémentaires', related_name='invited_employees', to='core.permission'),
        ),
    ]
