# Generated by Django 4.2.11 on 2026-01-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission_role'),
        ('hr', '0015_add_mode_to_qrcodesession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Rôle attribué à cet employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions personnalisées supplémentaires pour cet employé', related_name='employees_with_permission', to='core.permission'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
