# Generated by Django 5.2.8 on 2026-04-14 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_employee_invitation'),
        ('hr', '0015_add_custom_permissions_to_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Actif'), ('on_leave', 'En congé'), ('suspended', 'Suspendu'), ('terminated', 'Terminé')], default='active', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Organisation principale de l'employé")),
            ],
            options={
                'verbose_name': 'Appartenance employé',
                'verbose_name_plural': 'Appartenances employés',
                'db_table': 'hr_employee_memberships',
            },
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_organiz_4f239d_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='assigned_role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='termination_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Organisation de l'employé (legacy)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_legacy', to='core.organization'),
        ),
        migrations.AddField(
            model_name='employeemembership',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Rôle dans cette organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AddField(
            model_name='employeemembership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department'),
        ),
        migrations.AddField(
            model_name='employeemembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeemembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_memberships', to='core.organization'),
        ),
        migrations.AddField(
            model_name='employeemembership',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organizations',
            field=models.ManyToManyField(help_text="Organisations de l'employé", related_name='employees', through='hr.EmployeeMembership', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='employeemembership',
            index=models.Index(fields=['employee', 'organization'], name='hr_employee_employe_fb8008_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemembership',
            index=models.Index(fields=['organization', 'employment_status'], name='hr_employee_organiz_265108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeemembership',
            unique_together={('employee', 'organization')},
        ),
    ]
