# Generated by Django 4.2.11 on 2026-01-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0016_alter_role_unique_together_remove_role_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.AddField(
            model_name='department',
            name='head_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_heads', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
