# Generated by Django 5.2.8 on 2026-04-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_admin'),
        ('hr', '0016_add_employee_multi_organization_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodesession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_sessions', to='core.adminuser'),
        ),
    ]
