# Generated by Django 5.2.8 on 2026-02-05 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('alert', 'Alerte'), ('system', 'Système'), ('user', 'Utilisateur')], default='system', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Priorité')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('entity_type', models.CharField(blank=True, default='', help_text='ex : product, order, alert, employee …', max_length=100, verbose_name="Type d'entité liée")),
                ('entity_id', models.CharField(blank=True, default='', max_length=255, verbose_name="ID de l'entité liée")),
                ('action_url', models.CharField(blank=True, default='', max_length=500, verbose_name="URL d'action")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('organization', models.ForeignKey(help_text='Organisation à laquelle appartient cette notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization')),
                ('recipient', models.ForeignKey(help_text='Utilisateur destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.baseuser')),
                ('sender', models.ForeignKey(blank=True, help_text='Utilisateur qui a déclenché la notification (None = système)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='core.baseuser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date'), models.Index(fields=['organization', 'is_read'], name='idx_notif_org_read')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receive_alerts', models.BooleanField(default=True, verbose_name='Recevoir les alertes')),
                ('receive_system', models.BooleanField(default=True, verbose_name='Recevoir les notifications système')),
                ('receive_user', models.BooleanField(default=True, verbose_name='Recevoir les notifications utilisateur')),
                ('min_priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='low', help_text='Les notifications en dessous de cette priorité ne seront pas affichées', max_length=20, verbose_name='Priorité minimale')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.baseuser')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notification_preferences',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
