# Generated by Django 5.2.8 on 2026-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='Activer les notifications par email (nécessite Novu)', verbose_name='Recevoir par email'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone pour les notifications SMS (format international : +224...)', max_length=20, verbose_name='Numéro de téléphone SMS'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='Activer les notifications push navigateur/mobile', verbose_name='Recevoir les push'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Activer les notifications par SMS (nécessite Novu + crédits SMS)', verbose_name='Recevoir par SMS'),
        ),
    ]
