# Generated by Django 5.2.8 on 2025-12-24 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_logo_field'),
        ('hr', '0015_add_mode_to_qrcodesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nouvelle conversation', max_length=255)),
                ('is_agent_mode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField()),
                ('feedback', models.CharField(blank=True, choices=[('like', 'Utile'), ('dislike', 'Pas utile')], max_length=10, null=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_results', models.JSONField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField()),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='ai.message')),
            ],
            options={
                'verbose_name': "Exécution d'outil IA",
                'verbose_name_plural': "Exécutions d'outils IA",
                'ordering': ['-created_at'],
            },
        ),
    ]
