"""
Django settings for lourabackend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from urllib.parse import urlparse

# Load environment variables from .env file
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from backend/ directory (parent of app/)
ENV_PATH = BASE_DIR.parent / '.env'
if ENV_PATH.exists():
    load_dotenv(ENV_PATH)
    print(f"✅ Loaded .env from {ENV_PATH}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(0io1(8urv-qldqq2dh$!$*9-jt*wbrci^_d7y#_*9a*-qh5&w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# -----------------------------------------------------------------------------
# Helpers: normalize env inputs (hosts/origins)
# -----------------------------------------------------------------------------
def _normalize_host(value: str) -> str:
    """
    Accepts either "example.com" or "https://example.com:8000/path"
    and returns a host suitable for Django ALLOWED_HOSTS.
    """
    v = (value or "").strip()
    if not v:
        return ""
    if "://" in v:
        try:
            parsed = urlparse(v)
            v = parsed.hostname or ""
        except Exception:
            v = ""
    if ":" in v:  # "example.com:8000" -> "example.com"
        v = v.split(":", 1)[0].strip()
    return v

def _split_csv_env(value: str) -> list[str]:
    return [item.strip() for item in (value or "").split(",") if item.strip()]

# Allowed Hosts - supporte les variables d'environnement
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = []
    for raw in _split_csv_env(ALLOWED_HOSTS_ENV):
        host = _normalize_host(raw)
        if host:
            ALLOWED_HOSTS.append(host)
else:
    # Fallback safe defaults (hosts only, no scheme/port)
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '72.60.92.105','72-60-92-105.sslip.io']

# CSRF Trusted Origins - important pour les requêtes POST en production
CSRF_TRUSTED_ORIGINS_ENV = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = _split_csv_env(CSRF_TRUSTED_ORIGINS_ENV)
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://frontend-loura.vercel.app',
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://72.60.92.105:8000',
    ]

# Configuration CSRF supplémentaire
CSRF_COOKIE_HTTPONLY = False  # Permet l'accès JS au cookie CSRF (requis pour les SPAs)
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# En développement, autoriser CSRF depuis n'importe quelle origine
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(['https://frontend-loura.vercel.app', 'http://127.0.0.1:3000','http://localhost:3000','http://72.60.92.105:8000'])
    # Retirer les doublons
    CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS))


# Application definition

INSTALLED_APPS = [
    'daphne',  # IMPORTANT: Must be FIRST for WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # JWT token blacklist
    'channels',  # WebSocket support
    'core',
    'hr',
    'inventory',  # Inventory management
    'authentication',  # Centralized authentication
    'ai',  # AI Assistant module
    'notifications',  # Notifications interne
    'django_celery_beat',
    'django_celery_results',
]

# ---------------------------------------------------------------------------
# Celery Configuration
# ---------------------------------------------------------------------------
# Utilise Redis si configuré, sinon mode in-memory pour développement

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'memory://')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# En développement local (sans Redis), exécution synchrone
if CELERY_BROKER_URL == 'memory://':
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
else:
    # En production avec Redis, exécution asynchrone
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_TASK_EAGER_PROPAGATES = False

# Tâches périodiques (Celery Beat Schedule)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Vérifier les échéances de ventes à crédit tous les jours à 8h00
    'check-credit-sale-deadlines': {
        'task': 'inventory.tasks.check_credit_sale_deadlines',
        'schedule': crontab(hour=8, minute=0),  # Tous les jours à 8h00 UTC
        'options': {
            'expires': 3600,  # Expire après 1h si pas exécutée
        }
    },
    # Mettre à jour les statuts overdue tous les jours à 9h00
    'update-overdue-credit-sales': {
        'task': 'inventory.tasks.update_overdue_credit_sales',
        'schedule': crontab(hour=9, minute=0),  # Tous les jours à 9h00 UTC
        'options': {
            'expires': 3600,
        }
    },
    # Purger les anciennes notifications tous les lundis à 2h00
    'purge-old-notifications': {
        'task': 'notifications.tasks.purge_old_notifications_task',
        'schedule': crontab(hour=2, minute=0, day_of_week=1),  # Lundi à 2h00
        'kwargs': {'days': 30},  # Supprimer les notifications lues de plus de 30 jours
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.JWTAuthCookieMiddleware',  # JWT from cookies
    'authentication.middleware.TokenFromQueryParamMiddleware',  # JWT from query params
]

ROOT_URLCONF = 'lourabackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lourabackend.wsgi.application'


# Database
# Utilise PostgreSQL si les variables d'environnement sont définies, sinon SQLite

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', 'loura_db'),
            'USER': os.getenv('DB_USER', 'loura_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Persistent connections
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }
else:
    # SQLite par défaut pour développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', BASE_DIR.parent / 'staticfiles')

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'core.AdminUser'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'lourabackend.authentication.MultiUserJWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'lourabackend.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    # Use custom JSON renderer to handle UUIDs and other Django types
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
    'DEFAULT_RENDERER_CLASSES': [
        'lourabackend.renderers.UUIDJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# CORS Configuration - supporte les variables d'environnement
CORS_ALLOWED_ORIGINS_ENV = os.getenv('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS = _split_csv_env(CORS_ALLOWED_ORIGINS_ENV)
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # Next.js dev
        "http://127.0.0.1:3000",
        "https://frontend-loura.vercel.app",  # Vercel prod
    ]

# Autoriser cookies / authentification (si besoin) Si tu utilises JWT avec cookies, sessions ou authentification cross-domain :
CORS_ALLOW_CREDENTIALS = True

# En développement, autoriser tous les CORS (à retirer en prod finale)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Allow custom headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-organization-slug',  # Custom header for organization context
    'x-organization-subdomain',  # Custom header for organization subdomain
]

# JWT Configuration

SIMPLE_JWT = {
    # Access token settings
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Short-lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Refresh token valid for 7 days

    # Token types
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # Cookie settings for HTTP-only cookies
    'AUTH_COOKIE': 'access_token',  # Cookie name for access token
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # Cookie name for refresh token
    'AUTH_COOKIE_SECURE': os.getenv('AUTH_COOKIE_SECURE', str(not DEBUG)) == 'True',
    'AUTH_COOKIE_HTTP_ONLY': True,  # Prevents JavaScript access
    'AUTH_COOKIE_SAMESITE': 'Lax',  # CSRF protection
    'AUTH_COOKIE_PATH': '/',

    # Signing
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY if SECRET_KEY else 'fallback-secret-key-please-change',

    # Token behavior
    'ROTATE_REFRESH_TOKENS': True,  # Generate new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'UPDATE_LAST_LOGIN': True,

    # Token claims
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',


    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
}
# ==============================================================================
# ASGI & WebSocket Configuration (Django Channels)
# ==============================================================================
ASGI_APPLICATION = "lourabackend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        # Utilise Redis si la variable d'environnement est définie
        "BACKEND": os.getenv('CHANNEL_LAYERS_BACKEND', 'channels.layers.InMemoryChannelLayer'),
        "CONFIG": {
            "hosts": [os.getenv('CHANNEL_LAYERS_HOST', 'redis://localhost:6379/2')],
        } if os.getenv('CHANNEL_LAYERS_BACKEND') == 'channels_redis.core.RedisChannelLayer' else {},
    },
}

# ==============================================================================
# Novu — Notifications multi-canaux (Email, SMS, Push)
# ==============================================================================
# Activé uniquement si NOVU_ENABLED=True et NOVU_API_KEY est défini.
# Quand désactivé, seules les notifications in-app locales fonctionnent.
NOVU_ENABLED = os.getenv('NOVU_ENABLED', 'False') == 'True'
NOVU_API_KEY = os.getenv('NOVU_API_KEY', '')
NOVU_APPLICATION_IDENTIFIER = os.getenv('NOVU_APPLICATION_IDENTIFIER', '')

