# Generated by Django 5.2.8 on 2026-03-12 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Identifiant unique du module (ex: hr.employees, hr.payroll)', max_length=100, unique=True)),
                ('name', models.CharField(help_text="Nom d'affichage du module", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du module')),
                ('app_name', models.CharField(help_text="Nom de l'application Django associée (ex: hr, inventory)", max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icône du module (ex: Users, DollarSign, Calendar)', max_length=50)),
                ('category', models.CharField(default='general', help_text='Catégorie du module (ex: hr, finance, inventory)', max_length=50)),
                ('default_for_all', models.BooleanField(default=False, help_text='Si True, ce module est activé par défaut pour toutes les organisations')),
                ('default_categories', models.JSONField(blank=True, default=list, help_text='Liste des noms de catégories pour lesquelles ce module est activé par défaut')),
                ('requires_subscription_tier', models.CharField(blank=True, help_text="Niveau d'abonnement requis (ex: basic, premium, enterprise)", max_length=50)),
                ('depends_on', models.JSONField(blank=True, default=list, help_text='Liste des codes de modules requis')),
                ('is_core', models.BooleanField(default=False, help_text='Module core qui ne peut pas être désactivé')),
                ('is_active', models.BooleanField(default=True, help_text='Module actif et disponible')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Module activé pour cette organisation')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Paramètres spécifiques du module pour cette organisation')),
                ('enabled_at', models.DateTimeField(auto_now_add=True, help_text="Date d'activation du module")),
                ('enabled_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant activé le module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_modules', to='core.baseuser')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_modules', to='core.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_modules', to='core.organization')),
            ],
            options={
                'verbose_name': "Module d'organisation",
                'verbose_name_plural': "Modules d'organisations",
                'db_table': 'organization_modules',
                'ordering': ['module__order', 'module__name'],
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
