# Generated by Django 5.2.8 on 2026-03-31 15:16

from django.db import migrations, models


def copy_employee_data_to_baseuser(apps, schema_editor):
    """
    Copie les données personnelles des Employee vers BaseUser.
    Utilise SQL brut pour éviter les conflits de modèles pendant la migration.
    """
    # Vérifier si la table hr_employees existe
    cursor = schema_editor.connection.cursor()
    cursor.execute("""
        SELECT name FROM sqlite_master
        WHERE type='table' AND name='hr_employees';
    """)
    if cursor.fetchone() is None:
        # La table n'existe pas encore, ignorer
        return

    # Copier les données
    schema_editor.execute("""
        UPDATE base_users
        SET
            date_of_birth = hr_employees.date_of_birth,
            address = hr_employees.address,
            city = hr_employees.city,
            country = hr_employees.country,
            emergency_contact = hr_employees.emergency_contact
        FROM hr_employees
        WHERE base_users.id = hr_employees.baseuser_ptr_id;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_organizationmodule'),
        ('hr', '0001_initial'),  # Nécessaire pour accéder à la table hr_employees
    ]

    operations = [
        # Ajouter les colonnes directement via SQL pour éviter les conflits d'état
        migrations.RunSQL(
            # Forward SQL
            sql=[
                "ALTER TABLE base_users ADD COLUMN date_of_birth DATE NULL;",
                "ALTER TABLE base_users ADD COLUMN address TEXT NOT NULL DEFAULT '';",
                "ALTER TABLE base_users ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT '';",
                "ALTER TABLE base_users ADD COLUMN country VARCHAR(100) NOT NULL DEFAULT '';",
                "ALTER TABLE base_users ADD COLUMN emergency_contact TEXT NULL;",  # SQLite ne supporte pas JSONB, utilise TEXT
            ],
            # Reverse SQL
            reverse_sql=[
                "ALTER TABLE base_users DROP COLUMN date_of_birth;",
                "ALTER TABLE base_users DROP COLUMN address;",
                "ALTER TABLE base_users DROP COLUMN city;",
                "ALTER TABLE base_users DROP COLUMN country;",
                "ALTER TABLE base_users DROP COLUMN emergency_contact;",
            ]
        ),
        # Copier les données
        migrations.RunPython(
            copy_employee_data_to_baseuser,
            reverse_code=migrations.RunPython.noop
        ),
    ]
