# Generated by Django 4.2.11 on 2026-01-02 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_logo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique de la permission (ex: hr.view_employee)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nom lisible de la permission', max_length=200)),
                ('category', models.CharField(help_text='Catégorie de la permission (ex: Employés, Départements)', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'core_permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique du rôle (ex: super_admin, hr_manager)', max_length=100)),
                ('name', models.CharField(help_text='Nom du rôle', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='Rôle système prédéfini (non modifiable)')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organisation (null pour les rôles système)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions associées à ce rôle', related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'core_roles',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
