# Generated by Django 5.2.8 on 2026-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_personal_info_to_baseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict, help_text="Contact d'urgence (name, phone, relationship)", null=True),
        ),
    ]
